name: Build Debug APK
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build debug apk
        run: |
          ./gradlew assembleDebug
          mkdir da-output
          mv app/build/outputs/apk/debug/app-debug.apk da-output/LinuxDeployFork-debug.apk
      - name: Upload LinuxDeployFork-debug.apk to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: da-output/LinuxDeployFork-debug.apk

      - name: Upload debug apk to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: da-output/LinuxDeployFork-debug.apk
          overwrite: true